### ISSUE TITLE
Synchronization display

### ISSUE THREAD

**Issue by drnobodyphd** [drnobodyphd/DingViz#1]
In the short near future, there will be a lot of BLE devices in the lab and we will be testing synchronization algorithms in the lab.  Would it be possible to set up DingViz to somehow display the system syncing?  Currently, all nodes will transmit every X seconds, and nodes will adjust their phase to not collide with other nodes.  Would be interesting to perhaps see a ring or straight line of nodes, and then have them shuffle around as they change their phases?

**Comment by gsteinLTU** [comment]
We can do that. We could make the overall period an input and have the nodes put themselves on a timeline based on where in the cycle they last transmitted.

**Comment by gsteinLTU** [comment]
Already pretty much done in 7ae39db32a47cad705e275e41f9fbb5d0d554f94
